### ISSUE TITLE
go compose! 🛩️ 

### ISSUE THREAD

**Issue by Tautellini** [ColdTea-Projects/Moin#2]
Im watching. 😄 I see DiffUtils, Adapters, Delegates and XML Layouts. You know it, I know it, we all know it. There is only one way to deal with xml layouts and imperative UI patterns. (Dont take this one very serious XD)

**Comment by ColdTea-Projects** [comment]
sorry :( it is not necessary for this :) next project, I promise will be with compose :) thx!
